In [1]:
# install libraries 
# %pip install nltk sqlalchemy pymysql

In [2]:
from sqlalchemy import create_engine
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [3]:
# VADER lexicon for sentiment analysis
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\majd9\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [4]:
# connect to database
DB_PASSWORD = "your_password"
engine = create_engine('mysql+pymysql://root:DB_PASSWORD@localhost:3306/marketing_data_db')

In [5]:
# query to fetch customer reviews view
query = "SELECT * FROM fact_customer_reviews;"

In [6]:
# read data into a dataframe
customer_reviews_df = pd.read_sql(query, engine)
customer_reviews_df.sample(10)

,ReviewID,CustomerID,ProductID,ReviewDate,Rating,ReviewText
993,994,62,5,2025-11-27,5,Customer support was very helpful.
1330,1331,88,5,2025-06-02,4,The quality is top-notch.
113,114,52,19,2025-05-04,2,"Average experience, nothing special."
520,521,47,5,2024-03-31,2,Product did not meet my expectations.
959,960,81,2,2024-03-23,4,Customer support was very helpful.
1208,1209,53,10,2024-04-03,5,Five stars for the quick delivery.
957,958,45,1,2023-08-17,1,Not worth the money.
536,537,8,9,2023-03-11,4,Shipping was fast and the item was well-packaged.
532,533,92,6,2024-04-06,4,The quality is top-notch.
1245,1246,53,1,2024-08-04,4,The quality is top-notch.

In [7]:
sia = SentimentIntensityAnalyzer()

In [8]:
# get sentiment score of ReviewText column
def get_sentiment(review):
    if review:
        return sia.polarity_scores(str(review))['compound']
    return 0.0

In [9]:
# categorize sentiment based on Rating column and SentimentScore column
def categorize_sentiment(score, rating):
    if score >= 0.05:
        if rating >=4:
            return 'Positive'
        elif rating == 3:
            return 'Mixed Positive'
        else:
            return 'Contradictory'
    elif score < -0.05:
        if rating <=2:
            return 'Negative'
        elif rating == 3:
            return 'Mixed Negative'
        else:
            return 'Mixed Positive'
    else:
        if rating >= 4:
            return 'Positive'
        elif rating <=2:
            return 'Negative'
        else:
            return 'Neutral'

In [10]:
# categorize based on SentimentScore column only
def sentiment_bucket(score):
    if score >=0.5:
        return '(0.5 to 1.0) Strong Positive'
    elif 0.0 <= score < 0.5:
        return '(0.0 to 0.49) Moderate Positive'
    elif -0.5 <= score < 0.0:
        return '(-0.5 to -0.01) Moderate Negative'
    else:
        return '(-1.0 to -0.51) Strong Negative'

In [11]:
customer_reviews_df['SentimentScore'] = customer_reviews_df['ReviewText'].apply(get_sentiment)

In [12]:
customer_reviews_df['SentimentCategory'] = customer_reviews_df.apply(
    lambda row: categorize_sentiment(row['SentimentScore'], row['Rating']), axis=1)

In [13]:
customer_reviews_df['SentimentRange'] = customer_reviews_df['SentimentScore'].apply(sentiment_bucket)

In [14]:
customer_reviews_df.sample(5)

,ReviewID,CustomerID,ProductID,ReviewDate,Rating,ReviewText,SentimentScore,SentimentCategory,SentimentRange
54,55,57,9,2025-11-03,3,Customer support was very helpful.,0.6997,Mixed Positive,(0.5 to 1.0) Strong Positive
1202,1203,2,19,2025-07-20,4,"Great purchase, very satisfied.",0.8016,Positive,(0.5 to 1.0) Strong Positive
293,294,63,13,2023-11-09,3,Not worth the money.,-0.1695,Mixed Negative,(-0.5 to -0.01) Moderate Negative
1113,1114,56,15,2025-06-14,4,Shipping was fast and the item was well-packaged.,0.0000,Positive,(0.0 to 0.49) Moderate Positive
43,44,44,17,2023-04-20,5,"Excellent product, highly recommend!",0.7773,Positive,(0.5 to 1.0) Strong Positive

In [16]:
customer_reviews_df.to_sql('fact_customer_reviews_with_sentiment', con=engine, if_exists='replace', index=False)

1363